- README.md
- pom.xml
- src/org/wso2/tg/jenkins/Log.groovy
- src/org/wso2/tg/jenkins/alert/Email.groovy
- src/org/wso2/tg/jenkins/alert/Slack.groovy
- src/org/wso2/tg/jenkins/executors/TestExecutor.groovy
- src/org/wso2/tg/jenkins/util/AWSUtils.groovy
- src/org/wso2/tg/jenkins/util/Common.groovy
- test/UtilTest.groovy
- vars/Const.groovy
- vars/Pipeline.groovy
> Initial commit with source and other resources
> Bring out the common Jenkins execution code and make it a common library
> Initial commit with source and other resources

- src/org/wso2/tg/jenkins/util/AWSUtils.groovy
- vars/Pipeline.groovy
> Update pipeline script and AWSUtils

- vars/Pipeline.groovy
> Change testgrid-key name

- vars/Pipeline.groovy
> Merge master with dev

- src/org/wso2/tg/jenkins/alert/Email.groovy
- vars/Pipeline.groovy
> Merge Master

- src/org/wso2/tg/jenkins/util/AWSUtils.groovy
- vars/Pipeline.groovy
> Fix property loading issue

- src/org/wso2/tg/jenkins/alert/Email.groovy
- src/org/wso2/tg/jenkins/util/AWSUtils.groovy
- vars/Pipeline.groovy
> Updating production branch.

- src/org/wso2/tg/jenkins/executors/TestExecutor.groovy
> Fix no such method error

- src/org/wso2/tg/jenkins/alert/Email.groovy
> Add email bcc field

- vars/Pipeline.groovy
> Add new environment variable for define debug

- vars/Pipeline.groovy
job-config.yaml does not support "null" values for properties.
In case you put a null value, following error gets thrown. Adding quotes to values provides a temp fix.
Exception in thread "main" Cannot create property=properties for JavaBean=JobConfigFile{infrastructureRepository='workspace/testgrid/', deploymentRepository='workspace/testgrid/', scenarioTestsRepository='workspace/apim-test-integration', isRelativePaths=true, testgridYamlLocation='workspace/testgrid/jobs/wso2am-intg/testgrid.yaml', testgridKeyFileLocation='workspace/testgrid-key.pem'}
in 'reader', line 1, column 1:
keyFileLocation: workspace/testg ... 
^
in 'reader', line 7, column 3:
PRODUCT_GIT_URL: https://github. ... 
^
at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.ja …
> job-config.yaml does not support "null" values for properties

- vars/Pipeline.groovy
Parameterize the testgrid yaml entry that is hardcoded in the current implementation
> Parameterize testgrid yaml file entry

- vars/Pipeline.groovy
> Rename Debug flag 

- src/org/wso2/tg/jenkins/alert/Email.groovy
- vars/Pipeline.groovy
> Edit debug flag name in pipeline

- vars/Pipeline.groovy
This will adding the WUM related changes to the pipeline including debug flag.
Run integration tests through WUM product pack.
Added properties:
WUM_CHANNEL - ex: full/secure
PRODUCT_CODE - ex:wso2am
WUM_PRODUCT_VERSION: version of the product ex: 2.5.0
USE_CUSTOM_TESTNG: TRUE or FALSE (TRUE - Using custom testng.xml , FALSE - Using testng.xml in the product)
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type “Sent” when you have …
> Add WUM changes to the pipeline

- src/org/wso2/tg/jenkins/executors/TestExecutor.groovy
- vars/Pipeline.groovy
> Testing parallel run1

- src/org/wso2/tg/jenkins/executors/TestExecutor.groovy
> Remove additional brace

- src/org/wso2/tg/jenkins/executors/TestExecutor.groovy
> Remove addition term

- src/org/wso2/tg/jenkins/executors/TestExecutor.groovy
> Change of cmd sequence

- src/org/wso2/tg/jenkins/executors/TestExecutor.groovy
- vars/Pipeline.groovy
> Change code

- src/org/wso2/tg/jenkins/executors/TestExecutor.groovy
> Add more echos

- src/org/wso2/tg/jenkins/executors/TestExecutor.groovy
> Remove quotes

- vars/Pipeline.groovy
> Add another else block

- vars/Pipeline.groovy
> Change refering of env vars

- src/org/wso2/tg/jenkins/executors/TestExecutor2.groovy
> Remove debug argument from run-testplan command

- src/org/wso2/tg/jenkins/executors/TestExecutor2.groovy
> Removed additional inv. comma

- src/org/wso2/tg/jenkins/executors/TestExecutor2.groovy
> Add cleaning step to parallel workspace block at the begining

- vars/Pipeline.groovy
For WUM it needs to give support repo as the dist repo. It should provide user name and password in-order to access the repo. With this code change its constructing the product git url by append the username and password if the test mode is WUM. Username and password added as credentials in Jenkins.
> Brief description of the new feature or bug fix as it will appear in …
> Construct PRODUCT_GIT_URL

- src/org/wso2/tg/jenkins/executors/TestExecutor2.groovy
- src/org/wso2/tg/jenkins/util/AWSUtils.groovy
- src/org/wso2/tg/jenkins/util/Common.groovy
> Update TruncateTestPlan and S3Upload function for parallel executions

- src/org/wso2/tg/jenkins/executors/TestExecutor2.groovy
> Merging shell commands into shell blocks

- src/org/wso2/tg/jenkins/executors/TestExecutor2.groovy
> Suppress trace for echo command

- src/org/wso2/tg/jenkins/executors/TestExecutor2.groovy
> Removing suppression of  echo command with trace

- src/org/wso2/tg/jenkins/executors/TestExecutor2.groovy
- src/org/wso2/tg/jenkins/util/Common.groovy
> Add annotation to avoid serialize

- src/org/wso2/tg/jenkins/alert/Email.groovy
- src/org/wso2/tg/jenkins/executors/TestExecutor.groovy
- src/org/wso2/tg/jenkins/util/AWSUtils.groovy
- src/org/wso2/tg/jenkins/util/Common.groovy
- vars/Pipeline.groovy
> Production -> Dev

- vars/Pipeline.groovy
> Update Result Email title

- vars/Pipeline.groovy
Need to fetch the testplan.yaml as an environment property rather than hardcoding it.
> Add TestPlan.yaml property to fetch from Jenkins job

- vars/Pipeline.groovy
Reverts wso2-incubator/testgrid-jenkins-library#82
> Revert "Add TestPlan.yaml property to fetch from Jenkins job"

- src/org/wso2/tg/jenkins/executors/TestExecutor.groovy
- src/org/wso2/tg/jenkins/util/AWSUtils.groovy
- src/org/wso2/tg/jenkins/util/Common.groovy
Changes testplan directory name to testplan-id
> Changes testplan directory name to testplan-id

- src/org/wso2/tg/jenkins/executors/TestExecutor.groovy
- vars/Pipeline.groovy
Add the ability to change the executor count via passing an external parameter. **EXECUTOR_COUNT**
> Add parameterized executor count

- src/org/wso2/tg/jenkins/alert/Email.groovy
- src/org/wso2/tg/jenkins/executors/TestExecutor.groovy
- src/org/wso2/tg/jenkins/util/AWSUtils.groovy
- src/org/wso2/tg/jenkins/util/Common.groovy
- vars/Pipeline.groovy
> Sync Dev with Prod

- src/org/wso2/tg/jenkins/Properties.groovy
> Removing unnecessary properties
> Remove unnecessary properties

- vars/Pipeline.groovy
Add environment variables required for WUM
> Add environment variables required for WUM

- vars/Pipeline.groovy
Update environment varibles rquired for WUM
> Update environment variables required for WUM

- src/org/wso2/tg/jenkins/Properties.groovy
- src/org/wso2/tg/jenkins/util/Common.groovy
- vars/Pipeline.groovy
Fix WUM initializing issue due to null credentials
> Fix WUM initializing issue due to null credentials

- src/org/wso2/tg/jenkins/Properties.groovy
- src/org/wso2/tg/jenkins/util/Common.groovy
- vars/Pipeline.groovy
> Merge Dev with Production

- src/org/wso2/tg/jenkins/executors/TestExecutor.groovy
> Remove log truncation

- src/org/wso2/tg/jenkins/Properties.groovy
- vars/Pipeline.groovy
>  Update properties

- vars/Pipeline.groovy
Update pipeline with new file check method
> Update pipeline with new file check method

- src/org/wso2/tg/jenkins/Properties.groovy
> Update properties values

- src/org/wso2/tg/jenkins/Properties.groovy
- src/org/wso2/tg/jenkins/util/WorkSpaceUtils.groovy
Update properties values with empty
> Update properties values with empty

- src/org/wso2/tg/jenkins/executors/TestExecutor.groovy
> Fix spellings issue.

- src/org/wso2/tg/jenkins/executors/TestExecutor.groovy
> Fix skip-cloning issue.

- src/org/wso2/tg/jenkins/Properties.groovy
- src/org/wso2/tg/jenkins/util/WorkSpaceUtils.groovy
Fix deployment repository location
> Fix deployment repository location

- src/org/wso2/tg/jenkins/executors/TestExecutor.groovy
Fix dummy deploy.sh path location.
> Fix dummy deploy.sh path location

- src/org/wso2/tg/jenkins/executors/TestExecutor.groovy
Git private repos require credentials to clone. Hence, SSH key based credentials has been provided using the ssh-agent jenkins pipeline step.
SSH keys are recommended over username passwords for scripting purposes.
A new jenkins ssh private key credential has been added to both testgrid dev and prod.
N/A
> Use ssh keys to do clone git private repos

- src/org/wso2/tg/jenkins/Properties.groovy
- src/org/wso2/tg/jenkins/executors/TestExecutor.groovy
Add support to checkout git branch of infra/deploy/test repos
Yes
> Add support to checkout git branch of infra/deploy/test repos

- src/org/wso2/tg/jenkins/Properties.groovy
- vars/Pipeline.groovy
> Retrieve testgrid.yaml from a remote repository if available
> Retrieve testgrid.yaml from a remote repository if available

- src/org/wso2/tg/jenkins/Properties.groovy
- src/org/wso2/tg/jenkins/executors/TestExecutor.groovy
> Copy keyfile to TG_HOME for intg tests
> Copy ssh key file to TG_HOME for intg-tests

- src/org/wso2/tg/jenkins/Properties.groovy
- src/org/wso2/tg/jenkins/executors/TestExecutor.groovy
Clone multiple scenario repos given under ScenarioConfigs
> Clone multiple scenario repos

- src/org/wso2/tg/jenkins/Properties.groovy
- src/org/wso2/tg/jenkins/executors/TestExecutor.groovy
Fix issue in running multiple testplans
> Fix issue in running multiple testplans 

- vars/WebHookAnalyzer.groovy
Adding Webhook analyzing pipeline
A sample request would be 
```json
{
"ref": "refs/heads/master",
"before": "b5edec42491234470328996ca7a295bf4ca1b5ed",
"after": "902ed780f90e3a2b66826a8a99369c0c3757f22b",
"created": false,
"deleted": false,
"forced": false,
"base_ref": null,
"compare": "https://github.com/yasassri/web-hook-test/compare/b5edec424912...902ed780f90e",
"commits": [
{
"id": "902ed780f90e3a2b66826a8a99369c0c3757f22b",
"tree_id": "fbdee79958c039fd7c8a4a5e6162805678c64b88",
"distinct": true,
"message": "Update README.md",
"timestamp": "2018-12-04T14:41:07+05:30",
"url": "https://github.com/yasassri/web-hook-test/commit/902ed780f90e3a2b66826a8a99369c0c3757f22b",
"author": {
"name": "Yasassri Ratnayake",
"email": "ycrnet@gmail.com",
"username": "yasassri"
},
"committer": {
"name": …
```
> Adding Webhook analyzing pipeline

- src/org/wso2/tg/jenkins/util/ConfigUtils.groovy
The common config file cannot store sensitive credentials information. Hence we can use the Jenkins credentials plugin to store these values and retrieve the values during parameter population
Provide support for every kind of parameter types in common-configs files
`infra.secretValue=CREDENTIALS(secret-key)`
In order to retrieve the value from Jenkins credentials plugin, the entry should be as above. 
We identify that the value needs to be retrieved via the Credentials plugin by **CREDENTIALS()** notation
the value inside parentheses is used as the key for Jenkins credentials plugin.
- Confirmed that this PR doesn't commit …
> Resolve credential values in common-config file

- vars/JobCreatorPipeline.groovy
Provide support to configure the git repo and branch via the properties section of the testgrid-job-creator job.
ex.:
```
GIT_REPO=wso2/testgrid-job-configs
GIT_BRANCH=master
```
> Configure git repo/branch via properties section

- vars/JobCreatorPipeline.groovy
* Synchronize Jenkins with Git repo to gracefully recover from intermittent issues
* Add a job if a job config file actually contain a testgrid.yaml content.
#135
> Synchronize Jenkins with Git repo to gracefully recover from intermittent issues

- vars/Pipeline.groovy
> 
Add authorization support for Tesgrid yaml retrieval
>  Add authorization support for Tesgrid yaml retrieval

- src/org/wso2/tg/jenkins/util/ConfigUtils.groovy
- vars/Pipeline.groovy
>  Add Build environment and build status to the email subject
>  Add Build environment and build status to the email subject

- vars/Pipeline.groovy
Purpose of this change is to add nexus settings xml as a config file provider in the pipeline. This is only using for WUM test mode and build the UAT nexus artifacts before running the integration tests. 
> Link(s) to product documentation that addresses the changes of this PR. If no …
> Add UAT nexus settings xml as a config file provider in pipeline

- vars/Escalate.groovy
> Update escalation pipeline

- src/org/wso2/tg/jenkins/Properties.groovy
- src/org/wso2/tg/jenkins/alert/Email.groovy
- src/org/wso2/tg/jenkins/executors/TestGridExecutor.groovy
- vars/Escalate.groovy
Filter jobs for build-escalation email
> Filter jobs for build-escalation email

- src/org/wso2/tg/jenkins/executors/TestExecutor.groovy
- vars/Pipeline.groovy
- vars/WUMUpdateVerifier.groovy
Fix issue where success test plan builds that fail due to pipeline errors
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in …
> Fix issue where success test plan builds that fail due to pipeline errors

- .gitignore
- vars/JobCreatorPipeline.groovy
- vars/Pipeline.groovy
- vars/WUMUpdateVerifier.groovy
- vars/WebHookAnalyzer.groovy
In order to enable mask-password plugin, the pipeline blocks are being wrapped.
> Add wrappers in pipelines for mask-password plugin

- vars/ProdDeployerPipeline.groovy
- vars/WUMUpdateVerifier.groovy
Getting ready to send wum update overall results to a mailing list.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in …
> Styles for WUMUpdateVerifier

- src/org/wso2/tg/jenkins/Properties.groovy
- src/org/wso2/tg/jenkins/executors/TestExecutor.groovy
- src/org/wso2/tg/jenkins/executors/TestGridExecutor.groovy
- src/org/wso2/tg/jenkins/util/ConfigUtils.groovy
- vars/Pipeline.groovy
Reverts wso2/testgrid-jenkins-library#157
> Revert "Containerize run-testplan command execution"

- vars/WUMUpdateVerifier.groovy
> Integrating kubernetes resources into TestGrid. 
> Added a new step which will build images with WUM updates from UAT.
> Add wum updated image build

- src/org/wso2/tg/jenkins/executors/TestExecutor.groovy
Improve error logging in pipeline
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, …
> Improve error logging in pipeline

- src/org/wso2/tg/jenkins/executors/TestExecutor.groovy
> Unstash test plan before checking for test plan files
> Unstash test plans

- src/org/wso2/tg/jenkins/Properties.groovy
- src/org/wso2/tg/jenkins/executors/TestExecutor.groovy
- src/org/wso2/tg/jenkins/executors/TestGridExecutor.groovy
- vars/Pipeline.groovy
> Add changes that need to facilitate the local deployment of TestGrid.
> [WIP]  Changes needed when using the TestGrid local deployment

- vars/ProdDeployerPipeline.groovy
Fixes #167 
Change the remote location for downloading the MySQL connector jar.
> Fix MySQL connector jar download link

- vars/WUMUpdateVerifier.groovy
Removed 'build-docker-image' stage from the pipeline because at the moment K8s testing are not running in Testgrid and the implementation is going to be changed in future.
> Deprecated code

- src/org/wso2/tg/jenkins/executors/TestExecutor.groovy
> Add logs for debugging

- src/org/wso2/tg/jenkins/executors/TestGridExecutor.groovy
> Remove sleep

- src/org/wso2/tg/jenkins/executors/TestExecutor.groovy
> Print Stacktrace

- src/org/wso2/tg/jenkins/executors/TestExecutor.groovy
> Fix syntax error

- main.groovy
- scripts/os-level/instance-shutdown
> Add email receiver logic. Remove unwanted testing curl command.
> Add email receiver logic

- main.groovy
> Add another recipient's email address
> Add recipient email address

- scripts/apim/deploy.sh
- scripts/deployment-builder.sh
- scripts/is/deploy.sh
> Fix script path issues

- scripts/is/deploy.sh
> Exit when deployment fails

- parameters/parameters.json
> Update DB instance type

- parameters/ei/ei-samples.json
- scripts/ei/deploy.sh
> Add testgrid Jenkins scripts for EI

- main.groovy
> Update email list for product ei temporarily

- scripts/esb/deploy.sh
> Add testgrid Jenkins script for ESB

- parameters/parameters.json
> [main] Change infrastructure deployment key

- scripts/ei/deploy.sh
> Remove counter

- scripts/ei/deploy.sh
- scripts/esb/deploy.sh
> Remove backend deployment

- main.groovy
> Remove activemq back-end

- main.groovy
> [main] Update email list

- main.groovy
- scripts/deployment-handler.sh
> Add email credentials to deployment.properties

- main.groovy
> Add email credentials to parameter.json

- main.groovy
Revert https://github.com/wso2/testgrid-jenkins-library/commit/0c4869f7d2d854f13097daf0466bae549d3408ef
> Update email list

- main.groovy
> Fix syntax error in email sender

- README.md
- main.groovy
> support running on staging

- main.groovy
- scripts/mi/deploy.sh
> Add mi testgrid jenkins scripts

- main.groovy
> Add cloudformationLocation for product mi

- main.groovy
> Update cloudformationLocation for mi

- vars/WUMUpdateVerifier.groovy
> Add WUMUpdateVerifier for daily build

- vars/WUMUpdateVerifier.groovy
> Expose OS credentials

- vars/WUMUpdateVerifier.groovy
Reverts wso2/testgrid-jenkins-library#219
> Revert "Expose OS credentials"

- scripts/is/releases/release_distribution.sh
> This PR updates release pack
> Update Test pack

- vars/WUMUpdateVerifier.groovy
> Modify WUMUpdateVerifier for TGv2

- vars/WUMUpdateVerifier.groovy
- vars/get-wum-uat-products.sh
> Onboard daily batch job to TG v2

- scripts/ob/deploy.sh
> Add OB deploy.sh file

- main.groovy
> Add OB to main.groovy

- main.groovy
> Fix S3 path issue

- vars/get-wum-uat-products.sh
> Add apim to WUM batch job

- scripts/is/releases/release_distribution.sh
>This PR release_distribution.sh to download RC packs for which distribution value does not exist.
> Update script for RC packs

- integration.groovy
> Remove intg check

- vars/get-wum-uat-products.sh
> Onboard OB products

- integration.groovy
> Fix email send logic

- vars/get-wum-uat-products.sh
> Fix syntax error in WUM batch job script

- vars/get-wum-uat-products.sh
> Add OB build to the WUM batch job

- vars/clean-aws-cfn-stack.sh
> Add cleanup script to delete orphan cfn stacks

- scripts/os-level/instance-shutdown
> Add custom log directories for APIM

- scripts/ob/deploy.sh
> Update logic to wait till stack complete

- scripts/post-actions.sh
> $subject
- https://github.com/wso2-enterprise/cloud-sre-common/issues/279
> Add debug logs

- integration.groovy
> Add product download location to grv script
> Add product download location

- scripts/apim/intg/infra.json
> Add mapping for JDK 17

- scripts/intg-test-executer.sh
> Fix issue in product version script
> Fix issue in product version script

- kubernetes/product-deployment/main.jenkins
> Update default values

- kubernetes/product-deployment/main.jenkins
The existing credential is outdated. Updating this credential.
> Update AWS credentials

- kubernetes/manage-cluster/main.jenkins
Change outdated credential key
> Update AWS credentials for manage cluster

- kubernetes/manage-cluster/main.jenkins
Add newly created credentials for cluster creation
> Add new credentials for EKS cluster script

- kubernetes/product-deployment/main.jenkins
Change the credentials for the product deployment build to match the manage cluster build.
> Change credentials for the product deployment build

- integration.groovy
- scripts/intg-test-deployment.sh
- scripts/intg-test-executer.sh
Purpose
This PR will introduce executing APIM TG Integration build in groups so that when an intermittent test failure occurs, only the relevant group can be triggered to verify the builds
Related issue: https://github.com/wso2-enterprise/wso2-apim-internal/issues/4166
> Improve APIM TG Integration tests to execute in groups

- scripts/is/releases/release_distribution.sh
> Update product version in release_distribution.sh

- scripts/is/releases/release_distribution.sh
> Update product version to IS 7 RC6 in release_distribution.sh

- scripts/is/releases/release_distribution.sh
> Update product version to IS 7 RC7 in release_distribution.sh

- parameters/parameters.json
> Update the samples AMI

- parameters/parameters.json
> Use Rocky Linux AMI

- parameters/parameters.json
Reverts wso2/testgrid-jenkins-library#262
> Revert "Use Rocky Linux AMI"

- scripts/intg-test-deployment.sh
- scripts/intg-test-executer.sh
> Update scripts to kill the resources after test execution

- scripts/apim/intg/infra.json
Reverts wso2/testgrid-jenkins-library#265
> Revert "Update OpenJDK 11 version to 11.0.25_9"

- scripts/is/intg/infra.json
- scripts/is/intg/intg-deploy.sh
$subject
- https://github.com/wso2-enterprise/iam-engineering/issues/1121
> Add integration scripts and infra json to IS

- integration.groovy
- scripts/intg-test-executer.sh
**Purpose**
The current TestGrid build does not support running tests at the staging level. This PR adds support for executing tests in the staging state.
**Goals**
Enable running integration tests on a staging pack.
**Approach**
Pass UpdateType as an argument to wso2-update.sh
> Add staging update type and pass TEST_MODE to update script

- integration.groovy
- scripts/intg-test-executer.sh
Add isMigrated flag and a step to populate DB dumps for migration
> [Migration] Add Configurations for APIM Migration

- scripts/apim/intg/infra.json
Add Postgres related parameter into the URL string for APIM Migration.
> [APIM_MIGRATION] Add Postgres Related Parameter into the URL String

- ise2e.groovy
This PR introduces updates to the Jenkins Groovy pipeline script to support E2E test execution for WSO2 Identity Server within TestGrid. It addresses gaps in parameter handling and pipeline configuration required for seamless integration.
https://testgrid.wso2.com/job/RELEASE/job/E2E-Tests/job/product-is/job/is-7.2.0-alpha-e2e-testgrid-pipline/
Ensure that required parameters (such as product version, test suite configuration, and environment-specific variables) are properly defined and passed in the pipeline.
Align the pipeline structure with TestGrid’s execution flow for Identity Server E2E testing.
- Updated Groovy script to define and handle parameters needed for E2E test execution.
- Streamlined script logic to ensure compatibility with CloudFormation-based environment setup.
- …
> Add Jenkins Groovy pipeline to support IS E2E test execution on TestGrid
