wso2/testgrid-jenkins-library

vars/Pipeline.groovy
According to the new folder structure of the TestGrid job, `builds` directory will not be created.
=> Remove 'builds' dir from EmailReport location

src/org/wso2/tg/jenkins/util/AWSUtils.groovy
Remove unnecessary build directory from chart generation path
=> Remove unnecessary build directory from chart generation path

src/org/wso2/tg/jenkins/Properties.groovy, src/org/wso2/tg/jenkins/executors/TestExecutor.groovy, src/org/wso2/tg/jenkins/util/WorkSpaceUtils.groovy
This PR Changes the keys used for deployments. Now we have two different keys for prod and dev deployments. Which will be retrieved from Jenkins credentials plugin. 
> Secure testgrid deployment
> Retrieve deployment key from the Credentials plugin
=> Change the keys used for deployments 

src/org/wso2/tg/jenkins/executors/TestExecutor.groovy
Add option to skip cloning scenario repository when identical to infrastructure repository.
=> Add option to skip cloning scenario repository

src/org/wso2/tg/jenkins/Properties.groovy, src/org/wso2/tg/jenkins/executors/TestExecutor.groovy, src/org/wso2/tg/jenkins/util/WorkSpaceUtils.groovy
Remove getting redundant inputs of repository locations.
=> Remove getting redundant inputs of repository locations.

src/org/wso2/tg/jenkins/util/AWSUtils.groovy
S3 output is really verbose. This commit reduces that.
Use --only-show-errors flag in aws s3 sync.
=> Show only errors in S3 outputs

src/org/wso2/tg/jenkins/util/ConfigUtils.groovy, vars/Pipeline.groovy
There are properties that are used by TG jobs that are common across all the jobs. This PR introduces a common-configs.properties files that will specify these common configs, and they will be added to appropriate testgrid yaml sections upon processing.
Provide the properties that are always needed from testgrid side without user specifying it
A new config properties file is introduced via the config file provider plugin.
common.xxx=yyyy (insert the input parameter to all three sections)
infra.default.xxx=yyy (insert to input parameter section of infra section by default)
infra.xxx=yyy (insert to input parameter section of infra section only if the user has specified in the testgrid yaml file) in the testgridy.yaml the user can specify if that section needs a testgrid provided parameter …
=> Add support for common configs in multiple jobs

vars/JobCreatorPipeline.groovy, vars/jenkins.gdsl
We need to create testgrid jobs with git as the centralized place of control. This pipeline is added to automate the job creation.
Achieve full-automated GitOps
A testgrid job will be created in prod whenever a new yaml file is placed in this repo: https://github.com/wso2-incubator/testgrid-job-configs
That file must have the **testgridYamlURL** element that points to a valid testgrid.yaml file:
```
$> cat wum-sce-test-wso2am-2.1.0-full-testgrid.yaml
testgridYamlURL: https://raw.githubusercontent.com/kasunbg/testgrid-job-configs/master/wum-sce-test-wso2ei-6.4.0-full-testgrid.yaml
```
The testgrid.yaml files may reside on the product repos.
=> Add Gitops automatic testgrid job creation pipeline

pom.xml, src/org/wso2/tg/jenkins/executors/TestExecutor.groovy, src/org/wso2/tg/jenkins/executors/TestGridExecutor.groovy, src/org/wso2/tg/jenkins/util/Common.groovy
To provide quick access to the blue ocean dashboard for each build we generate the link in pipeline and provide it to RunTestPlan command to store in the database.
**Merge this after merging the related TestGrid PR to avoid any build breaks**
=> Provide blueocean link as an input to RunTestPlan command

src/org/wso2/tg/jenkins/executors/TestExecutor.groovy
Avoid hanging pipeline due to a dir not existing
There is a possibility to lost the directory for the parallel block if the parallel-executor got switched to another slave in the middle (due to a jenkins/tomcat restart, etc.)
This will ensure the pipeline would continue.
=> Avoid hanging pipline due to a dir not existing

src/org/wso2/tg/jenkins/Properties.groovy, src/org/wso2/tg/jenkins/alert/Email.groovy, vars/Pipeline.groovy
Sending a separate email to the infra script maintainers after a build with the infra error summary
If the infrastructure email is generated, send it to the infraEmailToList recipients.
=> Add infra email sending logic

src/org/wso2/tg/jenkins/Properties.groovy, src/org/wso2/tg/jenkins/executors/TestExecutor.groovy, src/org/wso2/tg/jenkins/executors/TestGridExecutor.groovy, src/org/wso2/tg/jenkins/util/ConfigUtils.groovy, vars/Pipeline.groovy
Containerize `run-testplan` command execution
Run a docker container and execute the run-testplan inside that.
The Dockerfile is available in https://github.com/wso2/testgrid/pull/1189
Docker Image is stored in an ECR in TestGrid AWS account.
https://github.com/wso2/testgrid/pull/1189
URI for docker image is added to config.propeties file in each environment as `TG_DOCKER_URI`
=> Containerize run-testplan command execution

vars/WUMUpdateVerifier.groovy
>  Exit 0 from the  [get-wum-uat-products.sh](https://github.com/wso2-incubator/test-integration-tests-runner/blob/master/get-wum-uat-products.sh) if no UAT update is found for a specific timestamp is not handled through Jenkins pipeline [WUMUpdateVerifier.groovy](https://github.com/NishikaDeSilva/testgrid-jenkins-library/blob/dev/vars/WUMUpdateVerifier.groovy)
> Alter [WUMUpdateVerifier.groovy](https://github.com/NishikaDeSilva/testgrid-jenkins-library/blob/dev/vars/WUMUpdateVerifier.groovy) to handle said purpose.
> Alter stage 'preparation' to check for new updates in UAT before proceeding further.
=> Add error handling if no new updated product is found in UAT.

src/org/wso2/tg/jenkins/Properties.groovy, src/org/wso2/tg/jenkins/executors/TestExecutor.groovy, src/org/wso2/tg/jenkins/util/ConfigUtils.groovy, vars/Pipeline.groovy
store service account access key in jenkins credential management and use it in the jenkins pipeline
The credential file is called in the jenkins pipeline and the credential file is used in the authentication process. After the validation, the file is deleted.
=> Testgrid Kubernetes support: Pipeline changes

src/org/wso2/tg/jenkins/Properties.groovy, src/org/wso2/tg/jenkins/executors/TestGridExecutor.groovy, src/org/wso2/tg/jenkins/util/WorkSpaceUtils.groovy, vars/Pipeline.groovy
> Improve the efficiency of Test Grid test running schedule and reduce the cost for Test Grid process.
> Reduce cost 
> Add more flexibility to the Test Grid schedule
> Automate the test running process
> Introduce scheduling method for test running as manual, daily, weekly and monthly. The test will be triggered automatically by time and using the date and day the pipeline will decide the running schedule and add the parameters according to that to jobcofig configuration file.
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
- Integration tests
> N/A
- Confirmed that this PR doesn't commit any keys, passwords, …
=>  Add run as schedule feature

vars/WUMUpdateVerifier.groovy
Add [1] to the notification so that team members can easily navigate to their respective builds.
[1] https://testgrid-live.private.wso2.com/admin/job/WUM/
Add TG build URL to the Email notification
- Ran FindSecurityBugs plugin and verified report? N/A
=> Add TG build URL to the Email notification

src/org/wso2/tg/jenkins/Properties.groovy, vars/Pipeline.groovy
> Right now, there is no option to parameterize the `label` of the Jenkins agent nodes. The `label` is used to specify which type of agent the job should run on. If someone wants to run some tests with a custom Jenkins agent, the only option is to fork this entire repo and change the `label` value under the `agent` section in Pipeline.groovy. With this fix, anyone can use a custom agent by simply specifying the parameter `agentNodeLabel` by selecting the `This project is parameterized` option in the configure section. 
> Provide support for custom Jenkins agents OOTB.
=> Parameterize the Jenkins agent label

vars/Escalate.groovy
> Remove the `jdk` config from the pipeline configuration. This way the `JAVA_HOME` will be picked from the environment variable preconfigured in the Jenkins master/slave node.
=> Remove tools config from pipeline def

src/org/wso2/tg/jenkins/Properties.groovy, vars/Pipeline.groovy
> According to the current implementation, once the infrastructure list has been configured in the config YAML file, there is no way to override it. Due to this, even if one infrastructure combination fails, all the other combinations also have to be tested since there is no way to temporarily override the infra list. This results in a waste or time and increased cost.
> With this fix, a new parameter named `infraOverrides` is introduced which can be specified via Jenkins prior to manually triggering the build. When this property is specified, it will override the list of infrastructures specified in the config YAML and only the list specified via this property will be considered when creating the test plans. The required infrastructure list should be entered as a comma-separated list as …
=> Provide the ability to override the infrastructure list via Jenkins

integration.groovy, main.groovy
Add new build param called apim_pre_release. Currently, the test grid only supports GA releases that are included in the AMI. The new param will help with future changes that we will add to support running integration tests on APIM pre-release versions.
=> Add apim-pre-release build param

scripts/apim/intg/infra.json
1. Removing unused OracleJDK 18 & 11
2. Adding Amazon CorrettoJDK 17
=> Update supported APIM JDK list

scripts/apim/intg/infra.json
This PR updates the OpenJDK 11 version used in testgrid to 11.0.25_9.
Related issue: https://github.com/wso2-enterprise/wso2-apim-internal/issues/7896
=> Update OpenJDK 11 version to 11.0.25_9
